services:
  online-mis-frontend:
    container_name: online-mis-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.pnpm 
    restart: unless-stopped
    ports:
      - "3000:3000"

  redis:
    container_name: online-mis-redis
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
