services:
  online-mis-frontend:
    container_name: online-mis-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.pnpm 
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - caddy
    depends_on: 
    - online-mis-backend
    - tailscale

  online-mis-backend:
    container_name: online-mis-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: service:tailscale
    depends_on: 
    - redis
    - tailscale
  
  redis:
    container_name: online-mis-redis
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=123
      - REDIS_PORT=6379
  
  tailscale:
    image: tailscale/tailscale:latest
    container_name: online-mis-tailscale
    hostname: online-mis-tailscale
    environment:
      - TS_AUTHKEY=
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=
      - TS_USERSPACE=false
    volumes:
      - tailscale-data:/var/lib/tailscale
    devices:
     - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped


networks:
  caddy: 
    external: true

volumes:
  tailscale-data:
    driver: local