/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as ConstructionImport } from './routes/construction'
import { Route as UserImport } from './routes/_user'
import { Route as UserHomeImport } from './routes/_user/home'
import { Route as UserAcademicNilaiSemesterImport } from './routes/_user/academic/nilai-semester'
import { Route as UserAcademicLogbookImport } from './routes/_user/academic/logbook'
import { Route as UserAcademicJadwalKuliahImport } from './routes/_user/academic/jadwal-kuliah'
import { Route as UserAcademicFrsOnlineMbkmImport } from './routes/_user/academic/frs-online-mbkm'
import { Route as UserAcademicAbsenImport } from './routes/_user/academic/absen'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ConstructionRoute = ConstructionImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => rootRoute,
} as any)

const UserRoute = UserImport.update({
  id: '/_user',
  getParentRoute: () => rootRoute,
} as any)

const UserHomeRoute = UserHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => UserRoute,
} as any)

const UserAcademicNilaiSemesterRoute = UserAcademicNilaiSemesterImport.update({
  id: '/academic/nilai-semester',
  path: '/academic/nilai-semester',
  getParentRoute: () => UserRoute,
} as any)

const UserAcademicLogbookRoute = UserAcademicLogbookImport.update({
  id: '/academic/logbook',
  path: '/academic/logbook',
  getParentRoute: () => UserRoute,
} as any)

const UserAcademicJadwalKuliahRoute = UserAcademicJadwalKuliahImport.update({
  id: '/academic/jadwal-kuliah',
  path: '/academic/jadwal-kuliah',
  getParentRoute: () => UserRoute,
} as any)

const UserAcademicFrsOnlineMbkmRoute = UserAcademicFrsOnlineMbkmImport.update({
  id: '/academic/frs-online-mbkm',
  path: '/academic/frs-online-mbkm',
  getParentRoute: () => UserRoute,
} as any)

const UserAcademicAbsenRoute = UserAcademicAbsenImport.update({
  id: '/academic/absen',
  path: '/academic/absen',
  getParentRoute: () => UserRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UserImport
      parentRoute: typeof rootRoute
    }
    '/construction': {
      id: '/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof ConstructionImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_user/home': {
      id: '/_user/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof UserHomeImport
      parentRoute: typeof UserImport
    }
    '/_user/academic/absen': {
      id: '/_user/academic/absen'
      path: '/academic/absen'
      fullPath: '/academic/absen'
      preLoaderRoute: typeof UserAcademicAbsenImport
      parentRoute: typeof UserImport
    }
    '/_user/academic/frs-online-mbkm': {
      id: '/_user/academic/frs-online-mbkm'
      path: '/academic/frs-online-mbkm'
      fullPath: '/academic/frs-online-mbkm'
      preLoaderRoute: typeof UserAcademicFrsOnlineMbkmImport
      parentRoute: typeof UserImport
    }
    '/_user/academic/jadwal-kuliah': {
      id: '/_user/academic/jadwal-kuliah'
      path: '/academic/jadwal-kuliah'
      fullPath: '/academic/jadwal-kuliah'
      preLoaderRoute: typeof UserAcademicJadwalKuliahImport
      parentRoute: typeof UserImport
    }
    '/_user/academic/logbook': {
      id: '/_user/academic/logbook'
      path: '/academic/logbook'
      fullPath: '/academic/logbook'
      preLoaderRoute: typeof UserAcademicLogbookImport
      parentRoute: typeof UserImport
    }
    '/_user/academic/nilai-semester': {
      id: '/_user/academic/nilai-semester'
      path: '/academic/nilai-semester'
      fullPath: '/academic/nilai-semester'
      preLoaderRoute: typeof UserAcademicNilaiSemesterImport
      parentRoute: typeof UserImport
    }
  }
}

// Create and export the route tree

interface UserRouteChildren {
  UserHomeRoute: typeof UserHomeRoute
  UserAcademicAbsenRoute: typeof UserAcademicAbsenRoute
  UserAcademicFrsOnlineMbkmRoute: typeof UserAcademicFrsOnlineMbkmRoute
  UserAcademicJadwalKuliahRoute: typeof UserAcademicJadwalKuliahRoute
  UserAcademicLogbookRoute: typeof UserAcademicLogbookRoute
  UserAcademicNilaiSemesterRoute: typeof UserAcademicNilaiSemesterRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserHomeRoute: UserHomeRoute,
  UserAcademicAbsenRoute: UserAcademicAbsenRoute,
  UserAcademicFrsOnlineMbkmRoute: UserAcademicFrsOnlineMbkmRoute,
  UserAcademicJadwalKuliahRoute: UserAcademicJadwalKuliahRoute,
  UserAcademicLogbookRoute: UserAcademicLogbookRoute,
  UserAcademicNilaiSemesterRoute: UserAcademicNilaiSemesterRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof UserRouteWithChildren
  '/construction': typeof ConstructionRoute
  '/login': typeof LoginRoute
  '/home': typeof UserHomeRoute
  '/academic/absen': typeof UserAcademicAbsenRoute
  '/academic/frs-online-mbkm': typeof UserAcademicFrsOnlineMbkmRoute
  '/academic/jadwal-kuliah': typeof UserAcademicJadwalKuliahRoute
  '/academic/logbook': typeof UserAcademicLogbookRoute
  '/academic/nilai-semester': typeof UserAcademicNilaiSemesterRoute
}

export interface FileRoutesByTo {
  '': typeof UserRouteWithChildren
  '/construction': typeof ConstructionRoute
  '/login': typeof LoginRoute
  '/home': typeof UserHomeRoute
  '/academic/absen': typeof UserAcademicAbsenRoute
  '/academic/frs-online-mbkm': typeof UserAcademicFrsOnlineMbkmRoute
  '/academic/jadwal-kuliah': typeof UserAcademicJadwalKuliahRoute
  '/academic/logbook': typeof UserAcademicLogbookRoute
  '/academic/nilai-semester': typeof UserAcademicNilaiSemesterRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_user': typeof UserRouteWithChildren
  '/construction': typeof ConstructionRoute
  '/login': typeof LoginRoute
  '/_user/home': typeof UserHomeRoute
  '/_user/academic/absen': typeof UserAcademicAbsenRoute
  '/_user/academic/frs-online-mbkm': typeof UserAcademicFrsOnlineMbkmRoute
  '/_user/academic/jadwal-kuliah': typeof UserAcademicJadwalKuliahRoute
  '/_user/academic/logbook': typeof UserAcademicLogbookRoute
  '/_user/academic/nilai-semester': typeof UserAcademicNilaiSemesterRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/construction'
    | '/login'
    | '/home'
    | '/academic/absen'
    | '/academic/frs-online-mbkm'
    | '/academic/jadwal-kuliah'
    | '/academic/logbook'
    | '/academic/nilai-semester'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/construction'
    | '/login'
    | '/home'
    | '/academic/absen'
    | '/academic/frs-online-mbkm'
    | '/academic/jadwal-kuliah'
    | '/academic/logbook'
    | '/academic/nilai-semester'
  id:
    | '__root__'
    | '/_user'
    | '/construction'
    | '/login'
    | '/_user/home'
    | '/_user/academic/absen'
    | '/_user/academic/frs-online-mbkm'
    | '/_user/academic/jadwal-kuliah'
    | '/_user/academic/logbook'
    | '/_user/academic/nilai-semester'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  UserRoute: typeof UserRouteWithChildren
  ConstructionRoute: typeof ConstructionRoute
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  UserRoute: UserRouteWithChildren,
  ConstructionRoute: ConstructionRoute,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_user",
        "/construction",
        "/login"
      ]
    },
    "/_user": {
      "filePath": "_user.tsx",
      "children": [
        "/_user/home",
        "/_user/academic/absen",
        "/_user/academic/frs-online-mbkm",
        "/_user/academic/jadwal-kuliah",
        "/_user/academic/logbook",
        "/_user/academic/nilai-semester"
      ]
    },
    "/construction": {
      "filePath": "construction.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_user/home": {
      "filePath": "_user/home.tsx",
      "parent": "/_user"
    },
    "/_user/academic/absen": {
      "filePath": "_user/academic/absen.tsx",
      "parent": "/_user"
    },
    "/_user/academic/frs-online-mbkm": {
      "filePath": "_user/academic/frs-online-mbkm.tsx",
      "parent": "/_user"
    },
    "/_user/academic/jadwal-kuliah": {
      "filePath": "_user/academic/jadwal-kuliah.tsx",
      "parent": "/_user"
    },
    "/_user/academic/logbook": {
      "filePath": "_user/academic/logbook.tsx",
      "parent": "/_user"
    },
    "/_user/academic/nilai-semester": {
      "filePath": "_user/academic/nilai-semester.tsx",
      "parent": "/_user"
    }
  }
}
ROUTE_MANIFEST_END */
